<?xml version="1.0"?>

<robot
    xmlns:xacro="http://ros.org/wiki/xacro"
    xmlns:interface="http://ros.org/wiki/xacro">
    
    <xacro:property name="M_PI" value="3.14159"/>
    
    <xacro:macro name="jasmine_ugv_tracks" params="t_base_size_x t_base_size_y t_base_size_z t_flipper_offset_x t_wheel_offset_y t_wheel_radius_big t_track_width">
        
            <xacro:arg name="add_raycast_self_filter_geom" default="false"/>
            <xacro:arg name="add_containment_self_filter_geom" default="false"/>
            
            <xacro:unless value="$(arg add_raycast_self_filter_geom)">
               
              <!--Make base geom larger for containment filter-->  
              <xacro:unless value="$(arg add_containment_self_filter_geom)">  
                <collision>  
                  <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                  <geometry>
                    <box size="${t_base_size_x*2} ${t_base_size_y*2} ${t_base_size_z*2}" />
                  </geometry>
                </collision>
              </xacro:unless>
              
              <xacro:if value="$(arg add_containment_self_filter_geom)">  
                <collision>  
                  <origin xyz="0.0 0.0 ${t_base_size_z*2}" rpy="0 0 0" />
                  <geometry>
                    <box size="${t_base_size_x*2} ${t_base_size_y*2} ${t_base_size_z*4}" />
                  </geometry>
                </collision>
              </xacro:if>
              <!--/Make base geom larger for containment filter-->  
              
              <collision>
                <origin xyz="0 ${-t_wheel_offset_y} 0.0" rpy="0 0 0"/>
                <geometry>
                  <box size="${t_base_size_x*2+t_flipper_offset_x*2} ${t_track_width} ${t_wheel_radius_big*2}"/>
                </geometry>
              </collision> 
              
              <collision>
                <origin xyz="0 ${t_wheel_offset_y} 0.0" rpy="0 0 0"/>
                <geometry>
                  <box size="${t_base_size_x*2+t_flipper_offset_x*2} ${t_track_width} ${t_wheel_radius_big*2}"/>
                </geometry>
              </collision> 
            </xacro:unless>
                    
            <xacro:if value="$(arg add_raycast_self_filter_geom)">
              <collision>
                <origin xyz="0.0 0.07 0.0" rpy="0 ${M_PI*0.5} 0" />
                <geometry>
                  <cylinder length="${t_base_size_x*2}" radius="${t_base_size_z*1.6}"/>
                </geometry>
              </collision>
              
              <collision>
                <origin xyz="0.0 -0.07 0.0" rpy="0 ${M_PI*0.5} 0" />
                <geometry>
                  <cylinder length="${t_base_size_x*2}" radius="${t_base_size_z*1.6}"/>
                </geometry>
              </collision>
              
              <collision>
                <origin xyz="0 ${-t_wheel_offset_y} 0.0" rpy="0 ${M_PI*0.5} 0"/>
                <geometry>
                  <cylinder length="${t_base_size_x*2}" radius="${t_wheel_radius_big}"/>  
                  <!--<box size="${t_base_size_x*2+t_flipper_offset_x*2} ${t_track_width} ${t_wheel_radius_big*2}"/>-->
                </geometry>
              </collision> 
              
              <collision>
                <origin xyz="0 ${t_wheel_offset_y} 0.0" rpy="0 ${M_PI*0.5} 0"/>
                <geometry>
                  <cylinder length="${t_base_size_x*2}" radius="${t_wheel_radius_big}"/>    
                  <!--<box size="${t_base_size_x*2+t_flipper_offset_x*2} ${t_track_width} ${t_wheel_radius_big*2}"/>-->
                </geometry>
              </collision> 
              
            </xacro:if>
                

            
            <collision>
              <origin xyz="${t_base_size_x+t_flipper_offset_x} ${-t_wheel_offset_y} 0.0" rpy="${M_PI/2} 0 0"/>
              <geometry>
                <cylinder length="${t_track_width}" radius="${t_wheel_radius_big}"/>
              </geometry>
            </collision>
      
            <collision>
              <origin xyz="${-t_base_size_x-t_flipper_offset_x}  ${-t_wheel_offset_y} 0.0" rpy="${M_PI/2} 0 0"/>
              <geometry>
                <cylinder length="${t_track_width}" radius="${t_wheel_radius_big}"/>
              </geometry>
            </collision>      
      

      
            <collision>
              <origin xyz="${t_base_size_x+t_flipper_offset_x} ${t_wheel_offset_y} 0.0" rpy="${M_PI/2} 0 0"/>
              <geometry>
                <cylinder length="${t_track_width}" radius="${t_wheel_radius_big}"/>
              </geometry>
            </collision>
      
            <collision>
              <origin xyz="${-t_base_size_x-t_flipper_offset_x}  ${t_wheel_offset_y} 0.0" rpy="${M_PI/2} 0 0"/>
              <geometry>
                <cylinder length="${t_track_width}" radius="${t_wheel_radius_big}"/>
              </geometry>
            </collision>      
      

        
    </xacro:macro>
</robot>
