<?xml version="1.0"?>

<robot
    xmlns:xacro="http://ros.org/wiki/xacro"
    xmlns:interface="http://ros.org/wiki/xacro">
    
    <xacro:include filename="$(find hector_tracked_vehicles_description)/urdf/tracked_wheel.urdf.xacro" />
    <xacro:include filename="$(find hector_tracked_vehicles_description)/urdf/jasmine_ugv_tracks.urdf.xacro" />
    <xacro:include filename="$(find hector_tracked_vehicles_description)/urdf/jasmine_ugv_base.gazebo.xacro" />
    <xacro:include filename="$(find hector_xacro_tools)/urdf/inertia_tensors.urdf.xacro" />
  
    
    <!-- Properties (Constants) -->
    <xacro:property name="M_PI" value="3.14159"/>
    
    <xacro:property name="base_size_x" value="0.255" />
    <xacro:property name="base_size_y" value="0.12" />
    <xacro:property name="base_size_z" value="0.045" />
    
    <xacro:property name="wheel_radius_big" value="0.080" />
    <xacro:property name="wheel_length" value="0.02" />
    <xacro:property name="wheel_size_y" value="0.0825" />

    <xacro:property name="track_width" value="0.0825" />    
    <xacro:property name="wheel_offset_y" value="0.1697" />
    <xacro:property name="flipper_offset_x" value="-0.04" />    
    

    <xacro:macro name="jasmine_ugv_macro">
        
        <xacro:arg name="add_default_geom" default="true"/>
        <xacro:arg name="add_containment_self_filter_geom" default="false"/>
        <xacro:arg name="add_raycast_self_filter_geom" default="false"/>
        
        <link name="base_link"/>
          
        <joint name="chassis_joint" type="fixed">
          <parent link="base_link"/>
          <child link="chassis_link"/>
        </joint>
        
        <link name="chassis_link">
          <xacro:inertial_cuboid_with_pose mass="10" x_length="${base_size_x*2}" y_length="${base_size_y*2}" z_length="${base_size_z*2}" >
            <origin xyz="0 0 0 " rpy="0 0 0" />
          </xacro:inertial_cuboid_with_pose>
          
            <visual>
                <origin xyz="0.0 0.0 -0.085" rpy="0 0 0" />
                <geometry>
                    <!--<box size="${base_size_x} ${base_size_y} ${base_size_z}" />-->
                    <mesh filename="package://hector_tracked_vehicles_description/meshes/jasmine_ugv/jasmine_ugv_simple_colored_v001.dae"/>
                </geometry>
                <material name="Grey" >
                    <color rgba="0.8 0.8 0.8 1"/>
                </material>                
            </visual>
            
            <!--Optional visualization of detailed mesh-->
            <!--
            <visual>
                <origin xyz="0.0 0.0 -0.049" rpy="0 0 0" />
                <geometry>
                    <mesh filename="package://hector_tracked_vehicles_description/meshes/jasmine_ugv/jasmine_2018_chassis_low_poly_velodyne.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name="Grey" >
                    <color rgba="0.8 0.8 0.8 1"/>
                </material>
            </visual>
            -->
            
            <!-- Chassis geometry -->
            <xacro:jasmine_ugv_chassis_geom t_base_size_x="${base_size_x}"  t_base_size_y="${base_size_y}" t_base_size_z="${base_size_z}"/>
        </link>
        
        <xacro:jasmine_ugv_track_link name="left_track" parent="chassis_link" t_wheel_radius_big="${wheel_radius_big}" t_track_width="${track_width}" t_track_length="${base_size_x*2+flipper_offset_x*2}">
          <origin xyz="0 ${wheel_offset_y} 0 " rpy="0 0 0" />  
        </xacro:jasmine_ugv_track_link>
        
        <xacro:jasmine_ugv_track_link name="right_track" parent="chassis_link" t_wheel_radius_big="${wheel_radius_big}" t_track_width="${track_width}" t_track_length="${base_size_x*2+flipper_offset_x*2}">
          <origin xyz="0 ${-wheel_offset_y} 0 " rpy="0 0 0" />  
        </xacro:jasmine_ugv_track_link>
            
        <xacro:tracked_vehicle_gazebo_plugin tracks_separation="${base_size_y + track_width}"/>
    </xacro:macro>
</robot>
