<?xml version="1.0"?>
<robot
  xmlns:xacro="http://ros.org/wiki/xacro" name="argo_tracker_structure_addons">
  <xacro:include filename="$(find hector_xacro_tools)/urdf/inertia_tensors.urdf.xacro"/>
  <xacro:include filename="$(find hector_sensors_description)/urdf/hokuyo_utm30lx.urdf.xacro" />
  <!--<xacro:include filename="$(find argo_tracker_description)/urdf/argo_tracker_$(optenv TRACKER_LIDAR_TYPE dual_hokuyo)_mount.urdf.xacro.xml" />-->
  <xacro:include filename="$(find hector_sensors_description)/urdf/generic_camera.urdf.xacro" />
  <!--<xacro:include filename="$(find argo_tracker_description)/urdf/manipulator_arm.urdf.xacro.xml" />-->
  
  
<!--  <xacro:arg name="add_self_filter_geom" default="0"/>-->
  <!--<xacro:property name="add_self_filter_geom" value="${arg add_self_filter_geom}"/>-->
  
  <xacro:property name="M_PI" value="3.14159265359"/>
  
  <xacro:property name="alu_profile_side_length" value="0.02"/>
  <xacro:property name="computer_box_height" value="0.15"/>
  <xacro:property name="computer_box_width" value="0.191"/>
  <xacro:property name="computer_box_length" value="0.191"/>
  <xacro:property name="top_protection_bottom" value="0.47"/>
  <xacro:property name="handle_width" value="0.07"/>
  <xacro:property name="handle_length" value="0.135"/>
  <xacro:property name="handle_height" value="0.016"/>
  <xacro:property name="handle_y" value="0.138"/>  
    
  
  <xacro:macro name="jasmine_2018_structure_addons_macro" params="parent *origin alu_profile_collision_size_factor name:='autonomy_box'">
      
    <xacro:arg name="add_containment_self_filter_geom" default="false"/>
      
    <joint name="${name}_joint" type="fixed">
      <xacro:insert_block name="origin"/>
      <parent link="${parent}" />
      <child link="${name}_link"/>      
    </joint>
    
     <joint name="imu_link_joint" type="fixed">
      <origin xyz="0 0 0.5" rpy="0 0 0"/>
      <parent link="${parent}" />
      <child link="imu_link"/>      
    </joint>
    
    <link name="${name}_link">
      <xacro:inertial_sphere mass="0.1" diameter="0.07"/>
      
      <!-- Computer box-->
      <visual>
        <origin xyz="0 0 ${computer_box_height/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${computer_box_length} ${computer_box_width} ${computer_box_height}"/>
        </geometry>
        <material name="Grey">
          <color rgba="0.5 0.5 0.5 1"/>
        </material> 
      </visual>

      <!--Protection vertical profiles-->
      <visual>
        <origin xyz="${ (computer_box_length/2-alu_profile_side_length/2)} ${ (computer_box_width/2-alu_profile_side_length/2)} ${computer_box_height/2 + top_protection_bottom/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${alu_profile_side_length} ${alu_profile_side_length} ${top_protection_bottom-computer_box_height}"/>
        </geometry>
        <material name="Grey">
          <color rgba="0.5 0.5 0.5 1"/>
        </material>  
      </visual>

      <visual>
        <origin xyz="${-(computer_box_length/2-alu_profile_side_length/2)} ${ (computer_box_width/2-alu_profile_side_length/2)} ${computer_box_height/2 + top_protection_bottom/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${alu_profile_side_length} ${alu_profile_side_length} ${top_protection_bottom-computer_box_height}"/>
        </geometry>
        <material name="Grey">
          <color rgba="0.5 0.5 0.5 1"/>
        </material>  
      </visual>
      
      <visual>
        <origin xyz="${-(computer_box_length/2-alu_profile_side_length/2)} ${-(computer_box_width/2-alu_profile_side_length/2)} ${computer_box_height/2 + top_protection_bottom/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${alu_profile_side_length} ${alu_profile_side_length} ${top_protection_bottom-computer_box_height}"/>
        </geometry>
        <material name="Grey">
          <color rgba="0.5 0.5 0.5 1"/>
        </material> 
      </visual>
      
      <visual>
        <origin xyz="${ (computer_box_length/2-alu_profile_side_length/2)} ${-(computer_box_width/2-alu_profile_side_length/2)} ${computer_box_height/2 + top_protection_bottom/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${alu_profile_side_length} ${alu_profile_side_length} ${top_protection_bottom-computer_box_height}"/>
        </geometry>
        <material name="Grey">
          <color rgba="0.5 0.5 0.5 1"/>
        </material> 
      </visual>
      
      <!--Top geom-->      
      <visual>
        <origin xyz="0 ${ (computer_box_width/2-alu_profile_side_length/2)} ${top_protection_bottom + alu_profile_side_length/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${computer_box_length} ${alu_profile_side_length} ${alu_profile_side_length}"/>
        </geometry>
        <material name="Grey">
          <color rgba="0.5 0.5 0.5 1"/>
        </material> 
      </visual>
      
      <visual>
        <origin xyz="0 ${-(computer_box_width/2-alu_profile_side_length/2)} ${top_protection_bottom + alu_profile_side_length/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${computer_box_length} ${alu_profile_side_length} ${alu_profile_side_length}"/>
        </geometry>
        <material name="Grey">
          <color rgba="0.5 0.5 0.5 1"/>
        </material> 
      </visual>

      <visual>
        <origin xyz="${ (computer_box_length/2-alu_profile_side_length/2)} 0 ${top_protection_bottom + alu_profile_side_length/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${alu_profile_side_length} ${computer_box_width}  ${alu_profile_side_length}"/>
        </geometry>
        <material name="Grey">
          <color rgba="0.5 0.5 0.5 1"/>
        </material> 
      </visual>
      
      <visual>
        <origin xyz="${-(computer_box_length/2-alu_profile_side_length/2)} 0 ${top_protection_bottom + alu_profile_side_length/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${alu_profile_side_length} ${computer_box_width}  ${alu_profile_side_length}"/>
        </geometry>
        <material name="Grey">
          <color rgba="0.5 0.5 0.5 1"/>
        </material> 
      </visual>     
      
      <!--Handles-->
      <!--     
      <visual>
        <origin xyz="0 ${ (computer_box_width/2+handle_width/2)} ${handle_y}" rpy="0 0 0"/>
        <geometry>
          <box size="${handle_length} ${handle_width} ${handle_height}"/>
        </geometry>
        <material name="Grey">
          <color rgba="0.5 0.5 0.5 1"/>
        </material> 
      </visual>
      
      <visual>
        <origin xyz="0 ${-(computer_box_width/2+handle_width/2)} ${handle_y}" rpy="0 0 0"/>
        <geometry>
          <box size="${handle_length} ${handle_width} ${handle_height}"/>
        </geometry>
        <material name="Grey">
          <color rgba="0.5 0.5 0.5 1"/>
        </material>  
      </visual>
      -->
      
      
      <!-- Computer box-->
      <xacro:unless value="$(arg add_containment_self_filter_geom)">
      <collision>
        <origin xyz="0 0 ${computer_box_height/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${computer_box_length} ${computer_box_width} ${computer_box_height}"/>
        </geometry>
        <material name="Grey">
          <color rgba="0.5 0.5 0.5 1"/>
        </material> 
      </collision>

      <!--Protection vertical profiles-->
      <collision>
        <origin xyz="${ (computer_box_length/2-alu_profile_side_length/2)} ${ (computer_box_width/2-alu_profile_side_length/2)} ${computer_box_height/2 + top_protection_bottom/2}" rpy="0 0 0"/>
        <geometry>
          <!--<box size="${alu_profile_side_length} ${alu_profile_side_length} ${top_protection_bottom-computer_box_height}"/>-->
          <cylinder length="${top_protection_bottom-computer_box_height}" radius="${alu_profile_side_length*0.5*alu_profile_collision_size_factor}"/>
        </geometry>
        <material name="Grey">
          <color rgba="0.5 0.5 0.5 1"/>
        </material>  
      </collision>

      <collision>
        <origin xyz="${-(computer_box_length/2-alu_profile_side_length/2)} ${ (computer_box_width/2-alu_profile_side_length/2)} ${computer_box_height/2 + top_protection_bottom/2}" rpy="0 0 0"/>
        <geometry>
          <!--<box size="${alu_profile_side_length} ${alu_profile_side_length} ${top_protection_bottom-computer_box_height}"/>-->
          <cylinder length="${top_protection_bottom-computer_box_height}" radius="${alu_profile_side_length*0.5*alu_profile_collision_size_factor}"/>
        </geometry>
        <material name="Grey">
          <color rgba="0.5 0.5 0.5 1"/>
        </material>  
      </collision>
      
      <collision>
        <origin xyz="${-(computer_box_length/2-alu_profile_side_length/2)} ${-(computer_box_width/2-alu_profile_side_length/2)} ${computer_box_height/2 + top_protection_bottom/2}" rpy="0 0 0"/>
        <geometry>
          <!--<box size="${alu_profile_side_length} ${alu_profile_side_length} ${top_protection_bottom-computer_box_height}"/>-->
          <cylinder length="${top_protection_bottom-computer_box_height}" radius="${alu_profile_side_length*0.5*alu_profile_collision_size_factor}"/>
        </geometry>
        <material name="Grey">
          <color rgba="0.5 0.5 0.5 1"/>
        </material> 
      </collision>
      
      <collision>
        <origin xyz="${ (computer_box_length/2-alu_profile_side_length/2)} ${-(computer_box_width/2-alu_profile_side_length/2)} ${computer_box_height/2 + top_protection_bottom/2}" rpy="0 0 0"/>
        <geometry>
          <!--<box size="${alu_profile_side_length} ${alu_profile_side_length} ${top_protection_bottom-computer_box_height}"/>-->
          <cylinder length="${top_protection_bottom-computer_box_height}" radius="${alu_profile_side_length*0.5*alu_profile_collision_size_factor}"/>  
        </geometry>
        <material name="Grey">
          <color rgba="0.5 0.5 0.5 1"/>
        </material> 
      </collision>
      
      <!--Top geom-->      
      <collision>
        <origin xyz="0 ${ (computer_box_width/2-alu_profile_side_length/2)} ${top_protection_bottom + alu_profile_side_length/2}" rpy="0 ${M_PI*0.5} 0"/>
        <geometry>
          <!--<box size="${computer_box_length} ${alu_profile_side_length} ${alu_profile_side_length}"/>-->
          <cylinder length="${computer_box_length}" radius="${alu_profile_side_length*0.5*alu_profile_collision_size_factor}"/>             
        </geometry>
        <material name="Grey">
          <color rgba="0.5 0.5 0.5 1"/>
        </material> 
      </collision>
      
      <collision>
        <origin xyz="0 ${-(computer_box_width/2-alu_profile_side_length/2)} ${top_protection_bottom + alu_profile_side_length/2}" rpy="0 ${M_PI*0.5} 0"/>
        <geometry>
          <!--<box size="${computer_box_length} ${alu_profile_side_length} ${alu_profile_side_length}"/>-->
          <cylinder length="${computer_box_length}" radius="${alu_profile_side_length*0.5*alu_profile_collision_size_factor}"/>
        </geometry>
        <material name="Grey">
          <color rgba="0.5 0.5 0.5 1"/>
        </material> 
      </collision>

      <collision>
        <origin xyz="${ (computer_box_length/2-alu_profile_side_length/2)} 0 ${top_protection_bottom + alu_profile_side_length/2}" rpy="${M_PI*0.5} ${M_PI*0.5} 0"/>
        <geometry>
          <!--<box size="${alu_profile_side_length} ${computer_box_width}  ${alu_profile_side_length}"/>-->
          <cylinder length="${computer_box_width}" radius="${alu_profile_side_length*0.5*alu_profile_collision_size_factor}"/>  
        </geometry>
        <material name="Grey">
          <color rgba="0.5 0.5 0.5 1"/>
        </material> 
      </collision>
      
      <collision>
        <origin xyz="${-(computer_box_length/2-alu_profile_side_length/2)} 0 ${top_protection_bottom + alu_profile_side_length/2}" rpy="${M_PI*0.5} ${M_PI*0.5} 0"/>
        <geometry>
          <!--<box size="${alu_profile_side_length} ${computer_box_width}  ${alu_profile_side_length}"/>-->
          <cylinder length="${computer_box_width}" radius="${alu_profile_side_length*0.5*alu_profile_collision_size_factor}"/>
        </geometry>
        <material name="Grey">
          <color rgba="0.5 0.5 0.5 1"/>
        </material> 
      </collision>     
      
      <!--Handles-->
      <!--     
      <collision>
        <origin xyz="0 ${ (computer_box_width/2+handle_width/2)} ${handle_y}" rpy="0 0 0"/>
        <geometry>
          <box size="${handle_length} ${handle_width} ${handle_height}"/>
        </geometry>
        <material name="Grey">
          <color rgba="0.5 0.5 0.5 1"/>
        </material> 
      </collision>
      
      <collision>
        <origin xyz="0 ${-(computer_box_width/2+handle_width/2)} ${handle_y}" rpy="0 0 0"/>
        <geometry>
          <box size="${handle_length} ${handle_width} ${handle_height}"/>
        </geometry>
        <material name="Grey">
          <color rgba="0.5 0.5 0.5 1"/>
        </material>  
      </collision>
      -->
      
      </xacro:unless>
      
      
      <xacro:if value="$(arg add_containment_self_filter_geom)">
      <collision>
        <origin xyz="0 0 ${computer_box_height/2 + top_protection_bottom/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${computer_box_length} ${computer_box_width} ${top_protection_bottom}"/>
        </geometry>
        <material name="Grey">
          <color rgba="0.5 0.5 0.5 1"/>
        </material> 
      </collision>
      <collision>
        <origin xyz="-0.18 0 ${computer_box_height/2+0.07}" rpy="0 0 0"/>
        <geometry>
          <box size="${computer_box_length} ${computer_box_width*1.95} ${0.3}"/>
        </geometry>
        <material name="Grey">
          <color rgba="0.5 0.5 0.5 1"/>
        </material> 
      </collision>
      
      </xacro:if>
    </link>
    
    <link name="imu_link">        
    </link>
    
    <gazebo reference="structure_addons_link">
      <material>Gazebo/Grey</material>
    </gazebo>
    
  </xacro:macro>
</robot>
