<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="flipper_base_mass" value="2.0"/>
  <xacro:property name="flipper_x" value="0.3"/>
  <xacro:property name="flipper_y" value="0.1"/>
  <xacro:property name="flipper_z" value="0.15"/>
  
  <!--
  Note macros below are exact copies of each with expection of the
  visual/collision tags.
  -->
  
  <xacro:macro name="flipper_geom_macro_visual" params="front">
    <visual>
      <material name="Grey" >
        <color rgba="0.8 0.8 0.8 1"/>
      </material>  
      <origin xyz="0 0 0" rpy="${M_PI*0.5} 0 0" />
      <geometry>
        <cylinder radius="${wheel_radius}" length="${flipper_width}" />
      </geometry>
    </visual>
    <visual>
      <origin xyz="${front*flipper_offset_wheel_axis_x} 0 0" rpy="${M_PI*0.5} 0 0" />
      <geometry>
        <cylinder radius="${wheel_radius}" length="${flipper_width}" />
      </geometry>
    </visual>
    <visual>
      <origin xyz="${front*flipper_offset_wheel_axis_x*0.5} 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${flipper_offset_wheel_axis_x} ${flipper_width} ${wheel_radius*2}" />
      </geometry>
    </visual>    
  </xacro:macro>
  
  <xacro:macro name="flipper_geom_macro_collision" params="front">
    <collision>
      <origin xyz="0 0 0" rpy="${M_PI*0.5} 0 0" />
      <geometry>
        <cylinder radius="${wheel_radius}" length="${flipper_width}" />
      </geometry>
    </collision>
    <collision>
      <origin xyz="${front*flipper_offset_wheel_axis_x} 0 0" rpy="${M_PI*0.5} 0 0" />
      <geometry>
        <cylinder radius="${wheel_radius}" length="${flipper_width}" />
      </geometry>
    </collision>
    <collision>
      <origin xyz="${front*flipper_offset_wheel_axis_x*0.5} 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${flipper_offset_wheel_axis_x} ${flipper_width} ${wheel_radius*2}" />
      </geometry>
    </collision>
  </xacro:macro>
  
  
  <xacro:macro name="obelix_flipper_macro" params="parent name front *origin">
    
    <!-- front is either 1 (for front flipper) or -1 (for back flipper) -->
    <!-- <joint name="${parent}_${name}_flipper_joint" type="fixed">   --> 
    <joint name="${name}_flipper_joint" type="revolute">    
      <xacro:insert_block name="origin"/>
      <axis xyz="0 1 0"/>
      <limit lower="${-90 * M_PI / 180}" upper="${90 * M_PI / 180}"
             effort="20000" velocity="${1.0 * 110 * M_PI / 180}" />
      
      <parent link="${parent}"/>
      <child link="left_${name}_flipper_base_link"/>
    </joint>
    
    <link name="left_${name}_flipper_base_link">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <xacro:inertial_cuboid_with_pose mass="3" x_length="${flipper_offset_wheel_axis_x}" y_length="${flipper_width}" z_length="${wheel_radius*2}" >
        <origin xyz="${front*flipper_offset_wheel_axis_x*0.5} 0 0" rpy="0 0 0" />
      </xacro:inertial_cuboid_with_pose>
      
      <xacro:flipper_geom_macro_visual front="${front}" />
      <xacro:flipper_geom_macro_collision front="${front}" />
      
    </link>    
    
    <joint name="right_${name}_flipper_joint" type="fixed">    
      <origin xyz="0 ${-2*flipper_offset_y} 0" rpy="0 0 0" />
      
      <parent link="left_${name}_flipper_base_link"/>
      <child link="right_${name}_flipper_base_link"/>
    </joint>
    
    <link name="right_${name}_flipper_base_link">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <xacro:inertial_cuboid_with_pose mass="3" x_length="${flipper_offset_wheel_axis_x}" y_length="${flipper_width}" z_length="${wheel_radius*2}" >
        <origin xyz="${front*flipper_offset_wheel_axis_x*0.5} 0 0" rpy="0 0 0" />
      </xacro:inertial_cuboid_with_pose>
      <xacro:flipper_geom_macro_visual front="${front}" />
      <xacro:flipper_geom_macro_collision front="${front}" />
    </link>
    
    <!--Needed for gazebo-->      
    <transmission name="${name}_flipper_joint_transmission">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${name}_flipper_joint">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </joint>  
      <actuator name="${name}_flipper_joint_motor">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>    
    
    <gazebo reference="${name}_left_flipper_base_link">
      <!--<material>Gazebo/Grey</material>-->
      <mu1>0</mu1>
      <mu2>0</mu2>
      <kp>1000000.0</kp>
      <kd>100.0</kd>
      <minDepth>0.001</minDepth>
      <maxVel>1.0</maxVel>
      <maxContacts>1</maxContacts>
    </gazebo>        
    
    <gazebo reference="${name}_right_flipper_base_link">
      <!--<material>Gazebo/Grey</material>-->
      <mu1>0</mu1>
      <mu2>0</mu2>
      <kp>1000000.0</kp>
      <kd>100.0</kd>
      <minDepth>0.001</minDepth>
      <maxVel>1.0</maxVel>
      <maxContacts>1</maxContacts>
    </gazebo>
    
  </xacro:macro>
</robot>
