<?xml version="1.0"?>

<robot name="obelix_ugv "
    xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
    xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
    xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface">
    
    <!-- Included URDF Files -->
    <include filename="$(find hector_tracked_vehicles_description)/urdf/obelix_2flipper_wheel.urdf.xacro" />
     <include filename="$(find hector_tracked_vehicles_description)/urdf/obelix_ugv_base.urdf.xacro" />

<obelix_ugv_macro />

  <!-- use for 4 flippers 
  <obelix_flipper_macro parent="base_link" name="left_front" front="1">
    <origin xyz="${base_size_x*0.5} ${base_size_y*0.5+wheel_offset_y+0.5*wheel_size_y}  0 " rpy="0 0 0"/>
  </obelix_flipper_macro > 

  
  <obelix_flipper_macro parent="base_link" name="right_front" front="1">
    <origin xyz="${base_size_x*0.5} ${-(base_size_y*0.5+wheel_offset_y+0.5*wheel_size_y)}  0  " rpy="0 0 0"/>
  </obelix_flipper_macro > 

  <obelix_flipper_macro parent="base_link" name="right_back" front="-1">
    <origin xyz="${-base_size_x*0.5} ${-(base_size_y*0.5+wheel_offset_y+0.5*wheel_size_y)}  0  " rpy="0 0 0"/>
  </obelix_flipper_macro > 


<obelix_flipper_macro parent="base_link" name="left_back" front="-1">
    <origin xyz="${-base_size_x*0.5} ${(base_size_y*0.5+wheel_offset_y+0.5*wheel_size_y)}  0  " rpy="0 0 0"/>
  </obelix_flipper_macro > -->

  <!-- use for 2*2 flippers --> 
  <obelix_flipper_macro parent="base_link" name="front" front="1">
    <origin xyz="${base_size_x*0.5} ${base_size_y*0.5+wheel_offset_y+0.5*wheel_size_y}  0 " rpy="0 0 0"/>
  </obelix_flipper_macro > 

  <obelix_flipper_macro parent="base_link" name="back" front="-1">
    <origin xyz="${-base_size_x*0.5} ${(base_size_y*0.5+wheel_offset_y+0.5*wheel_size_y)}  0  " rpy="0 0 0"/>
  </obelix_flipper_macro >

  
</robot>
